### ISSUE TITLE
[tests] Header component

### ISSUE THREAD

**Issue by shayc** [cboard-org/cboard#120]
The `Header` component is a simple component appearing on all pages.
Needs tests

**Comment by arthurdenner** [comment]
Which kind of tests do you want to make? Also, how do you prefer to build the tests? Seems like a simple question, but would be nice to estabilish this so we can make resilient tests.

I wrote some tests to this `Header` component, but I don't know if they're useful and/or enough.

```
import React from 'react';
import { mount, shallow } from 'enzyme';
import AppBar from 'material-ui/AppBar';
import Header from './Header';

it('renders without crashing', () => {
  const wrapper = shallow(<Header />);

  expect(wrapper).toBeTruthy();
});

it('renders with defaultProps', () => {
  const wrapper = mount(<Header />);

  expect(wrapper.find(AppBar).prop('className')).toEqual(
    'Header Header-AppBar-1'
  );
});

it('renders with passed props', () => {
  const wrapper = mount(<Header className="test" />);

  expect(wrapper.find(AppBar).prop('className')).toEqual(
    'Header test Header-AppBar-1'
  );
});

it('renders with children, if there are any', () => {
  const wrapper = mount(
    <Header>
      <div className="test-div" />
    </Header>
  );

  expect(wrapper.find('div.test-div')).toHaveLength(1);
});
```

**Comment by shayc** [comment]
It's a good question, if you have any thoughts please share, I'm checking for best practices on react/jest testing and will come up with findings. The tests you wrote seems fine to me, it's a simple component.

**Comment by arthurdenner** [comment]
I really like what Kent C. Dodds wrote in [this article](https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269) and I think we should use the `data-test` approach. However, I found a very strange behaviour applying this approach to the `Header` component.

I tried to write the tests using `data-test` and I'm getting this errors.

![image](https://user-images.githubusercontent.com/13774309/33963254-7eb844a2-e03b-11e7-95a9-77b3b54ea977.png)
![image](https://user-images.githubusercontent.com/13774309/33963407-f1db57c6-e03b-11e7-9daf-81e11591c3f4.png)
![image](https://user-images.githubusercontent.com/13774309/33963289-9d969db0-e03b-11e7-84df-fd6683aa49e7.png)

They only work if I do:

![image](https://user-images.githubusercontent.com/13774309/33963339-c62cc7d6-e03b-11e7-88bf-fab5b35eb861.png)

The weirdest thing is: If I change the container to a `div` instead of `AppBar`, the tests passes.

![image](https://user-images.githubusercontent.com/13774309/33963439-1755cc98-e03c-11e7-8039-c92cfc6ccd9d.png)
![image](https://user-images.githubusercontent.com/13774309/33963457-266ef5d8-e03c-11e7-8c5f-6f37b46e3682.png)

**Comment by arthurdenner** [comment]
The main point of this approach is: if we decide to change from Material-UI to any other UI framework, for example, the test below would break, what shouldn't happen.

```
it('renders with defaultProps', () => {
  const wrapper = mount(<Header />);

  expect(wrapper.find(AppBar).prop('className')).toEqual(
    'Header Header-AppBar-1'
  );
});
```

Using `data-test` we wouldn't encounter this problems because whatever wrapper we decide to the component would still have the `data-test` attribute.

I'll write some tests using `data-test` attributes so we can have a "bigger picture" to judge if we should or shouldn't use it definitively. I'll raise a PR with this in a couple of days.

**Comment by arthurdenner** [comment]
PS: the `Header` component isn't being used, maybe you can delete it?
I'll write the tests in some other components.

**Comment by shayc** [comment]
deleted! thanks
