### ISSUE TITLE
Imported boards from  the open board formats (obf and obz files) should be imported as "fixed board" in order to don't loose the tiles positions

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1232]
We want more transparency for the open board formats (obf and obz files) that are imported into cboard. The boards should keep the dimensions and the position of the tiles as the original board. 
examples: 
https://www.openboardformat.org/examples

**Comment by eadraffan** [comment]
I think this is invaluable as I have had problems in the past with cells / tiles moving when I change the aspect and your edit mode for fixing the settings is really useful.  To get this to happen with my imported obf boards from Board Builder (in Global Symbols)  would be wonderful!!   I still cannot get the obz linked boards to work and have to do the linking from within Cboard.  This is something we are going to check our end to make sure it is not our method for linking the boards rather than your importing system.
