### ISSUE TITLE
Display Subscription management instead of plans if the user is already subscribed 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1390]
If the user is subscribed, a few options should be displayed instead of showing the available plans. The two options that must be shown are: 

- Pause payment 
- Cancel subscription 

Below is a screenshot example of the look and feel: 

![subscription](https://user-images.githubusercontent.com/8397930/221387027-68e8b98b-b437-4024-8d1f-4a52dad453b3.png)

**Comment by RodriSanchez1** [comment]
We can avoid the use of subscription pause because annual subscriptions cannot be paused.
Now its disabled on play store console. Also, is not handled that scenario on the code yet. 
[Here](https://developer.android.com/google/play/billing/subscriptions#pause) you can find more info about paused subscriptions.
