### ISSUE TITLE
Error trying to reproduce tiles with web sources - IOS

### ISSUE THREAD

**Issue by tomivm** [cboard-org/cboard#1499]
The problem occurs when the user is logged and record a sound with an internet connection. the source is accessible via a web URL.
Unhandled Promise Rejection: NotSupportedError: The operation is not supported.

**Comment by jmdetloff** [comment]
It seems this is caused by safari lacking native support for ogg audio. https://stackoverflow.com/questions/47962500/unhandled-promise-rejection-notsupportederror-dom-exception-9-the-operation
You may need to vend audio for iOS in a different format, or find a cordova plugin that supports ogg audio, or I imagine there are cocoapods for ogg playback that could be used.

**Comment by tomivm** [comment]
Thanks for your help @jmdetloff
