### ISSUE TITLE
Create a release pipeline in Circle CI

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#729]
The pipeline must:

- Be triggered when a release tag is created in Github.
- Deploy the web app to production.
- Build the Android app.
- Deploy the Android app on Google Play store.
- Run smoke tests against production.

**Comment by sylvansson** [comment]
I did some research. For the first point, it looks like we'll need to create release tags through the terminal rather than the Github UI, because CircleCI only listens to the [`push`](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push) webhook, and not [`release`](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release). See https://discuss.circleci.com/t/is-it-possible-to-trigger-builds-workflows-from-github-tag-creation-from-githubs-ui-not-tag-push/33138.

(I can work on this, but I'm not familiar with CircleCI. I don't know how long it would take me.)

**Comment by martinbedouret** [comment]
@sylvansson I'm good you could take this if you want to learn about circle CI. This is a long task and it doesn't block anything, so you can work on it gradually if you want.

**Comment by martinbedouret** [comment]
done! See the following link https://github.com/cboard-org/ccboard/blob/master/.circleci/config.yml
