### ISSUE TITLE
When Serbian with Cyrillic is chosen, symbols from Global Symbols set are shown in Latin 

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#736]
When Serbian with Cyrillic is chosen, symbols from Global Symbols set are shown in Latin while in Edit mode and wanting to search symbols.

**Comment by martinbedouret** [comment]
Serbian is a very special case since the Global symbols API does not allow to specify the script type (cyrillic or latin). This will require some coordination with the Global symbols people. Assigned to me.

**Comment by martinbedouret** [comment]
@mzilak what I can see is that Global symbols is returning the symbols labels depending on the alphabet you use for the search. So if you use **Cyrillic** characters, you get the following:

![image](https://user-images.githubusercontent.com/8397930/86501844-48e3d180-bd73-11ea-9041-6ef4a71f1d74.png)

And if you use **Latin** characters, you get the following:

![image](https://user-images.githubusercontent.com/8397930/86501866-7761ac80-bd73-11ea-8d87-d515c6a62641.png)

To me, this is correct since Serbian is a single language with two scripting types. Global symbols API just recognizes a single language that is Serbian, there is no way to tell the API we want just Cyrillic or Latin, it will depend on the characters you type.
Sounds that good ?

**Comment by martinbedouret** [comment]
looping @eadraffan

**Comment by mzilak** [comment]
@martinbedouret , yeah, this is correct, when searching with Cyrillic or Latin characters to get search results with that alphabet. The thing is when the Cyrillic is selected and when in editing mode and you want to search for a symbol, you click on the magnifier, and half od the symbols (Mullbery) are shown with Cyrillic labels, and half of them (from GlobalSymbols) are shown with Latin labels. Since the user interface and Mullbery symbols are shown in Cyrillic, we think that it would be the best to show symbols from Global Symbols also in Cyrillic (if possible).

**Comment by eadraffan** [comment]
Please can I ask a question that is worrying me. Why can I not choose Serbian, Croatian or Montenegrin languages in the settings of the Cboard version I have downloaded? This would allow me to change the interface language and search in Cyrillic on GlobalSymbols as I can do with Russian and find Bliss symbols.    I think this is where the problem lies - is there a special version that is being used by you all and I am missing something?  On Boardbuilder we have the languages set separately from the interface so I can test for the symbols that might be causing problems, but also this allows me to create boards in different languages.  I will get back to Russell to see what we can do.

**Comment by martinbedouret** [comment]
@eadraffan yes, that is due that Alfanum has released a TTS engine for each one of the languages, so there is one for Croatian, one for Serbian and one for Montenegro. You have to install all three in your device. I am sending you the apk's by email.

**Comment by eadraffan** [comment]
Thank you

**Comment by martinbedouret** [comment]
I'm closing this for now as the functionality is working fine.
