### ISSUE TITLE
SVG images won't display after import of an OBZ board 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#765]
1. Import the attached board, it contains local  images on PNG and SVG formats.
2. Check the board on the Cboard ui
3. SVG Image is lost

[Coughdrop CommuniKate Action.zip](https://github.com/cboard-org/cboard/files/5016106/Coughdrop.CommuniKate.Action.zip)

**Comment by sylvansson** [comment]
@martinbedouret Which image is missing specifically? I investigated and found that roughly 90% of SVG images in the attached OBZ file have an invalid MIME type (`image/svg` instead of `image/svg+xml`), so we construct an invalid data URI that the frontend cannot render.

```javascript
// board_1_243.obf
{
  "id": "1_2931_15dbc4fe5664dd97760c86ed",
  "content_type": "image/svg", // should be `image/svg+xml`
  "path": "images/image_1_2931_15dbc4fe5664dd97760c86ed.svg"
}
```

```
// Template
data:<content-type>;base64;<encoded-image>
// Valid
data:image/svg+xml;base64,PD94b...
// Invalid
data:image/svg;base64,PD94b...
```

I think we could easily handle this by detecting the MIME type ourselves based on the filename using the [`mime-types`](https://github.com/jshttp/mime-types) library. However, I don't know whether we really want to support invalid configurations.

**Comment by martinbedouret** [comment]
@sylvansson yes, let's fix the MIME types if possible. The other issue I saw is that images are saving in cloud storage without file extension:

![image](https://user-images.githubusercontent.com/8397930/89430603-46c7b680-d715-11ea-8d5a-c846d13f724c.png)

**Comment by sylvansson** [comment]
The simplest fix would be to replace `image/svg` with `image/svg+xml` when we encounter it, and eventually we could look into detecting the MIME type automatically as mentioned in https://github.com/cboard-org/cboard/issues/765#issuecomment-668942339.

Should we create a separate issue for the missing extension?

**Comment by martinbedouret** [comment]
yes let's handle the extension stuff as a separate issue.

**Comment by sylvansson** [comment]
Great. I should have a PR for this issue by Friday night.
