### ISSUE TITLE
Imported board with folders (Cboard format) has "missed folders"

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#773]
After the board that has folders is exported from Cboard and then imported back into Cboard (different user), the folders appear as missing (message: We are sorry but we have missed this folder / board. We recommend you to create it again.).

However, if the board and the folders are exported and imported one by one, they will connect correctly and will not be missed.

**Comment by martinbedouret** [comment]
@sylvansson Could you please take a look at this?

**Comment by sylvansson** [comment]
@martinbedouret This happens because we only export the "root" board and exclude nested boards, even though we still reference nested boards in the `loadBoard` property. I think it would make sense to include nested boards in the generated JSON file. What do you think?

We also exclude nested boards when exporting to the Open Board Format, but we don't reference them anywhere, so folders become regular buttons when re-imported.
