### ISSUE TITLE
Importing boards from .json file gives warning "Nothing to import"

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#789]
I exported all my boards from one account and imported them successfully while not logged in. After that I logged in to another account (not the one from which I exported the boards) and after trying to import the same .json file, I get the message: Warning: there is nothing in this file to import.
![Screenshot_20200903-144126_Cboard](https://user-images.githubusercontent.com/57595384/92124484-21a29280-edfe-11ea-99ce-1209e83cd82c.jpg)

After that I again tried to import the boards from the same .json file while not logged in and again it was successful.

**Comment by martinbedouret** [comment]
@sylvansson Could you please take a look at this?

**Comment by sylvansson** [comment]
I will investigate tonight. @mzilak Did you have custom boards in your export, or only default ones?

**Comment by sylvansson** [comment]
This seems to be the expected behaviour. If I create or import boards while logged out, and then log into my account, new boards are automatically added to my account. The notification in the screenshot is only shown when the boards in the import file are already found in the account, based on their id.

@mzilak Could you log into your account and see if the boards you wanted to import are already there?

**Comment by mzilak** [comment]
@sylvansson , I had both, the default ones and custom boards in my export. 
I tried to reproduce this once again and I got the same result/warning. Then I checked and I guess you are right, the boards were automatically imported, but not all of them, I checked the json file and tried to compare the boards, and there are still some of the boards that are missing on another account.
Nevertheless, I think that this could be confusing for some users if they import by accident the json file while they are not logged in and then try to import the boards after they log in. Maybe different message or with additional explanation could be more helpful, e.g. Warning: there is nothing in this file to import, we already imported all newly discovered boards or something like this.

**Comment by sylvansson** [comment]
@mzilak Thank you for checking. I will investigate one more time tonight to make sure my assessment is correct. I haven't done any troubleshooting on Cboard's production environment yet, but if you attach the JSON file and give me the email for the acccount with the missing boards, I could look into it.

If the information is sensitive, you could send it to me on [our Discord](https://discord.gg/TEH8uxh).

If my assessment is correct and boards are added automatically, I agree with you that we should notify the user or perhaps let them choose whether or not to add them in the first place.

**Comment by mzilak** [comment]
@sylvansson the account I used is for testing purposes so you can take a look: uniceftest89@gmail.com (password: uniceftestpass89). I attached the json file here, as well (I zipped it because json file type is not supported)
[2020-09-28_14-10-09-boardsset board.zip](https://github.com/cboard-org/cboard/files/5292361/2020-09-28_14-10-09-boardsset.board.zip)
.

**Comment by sylvansson** [comment]
Thank you @mzilak, I'll take a look tonight. I encourage you to change the password afterwards.

**Comment by mzilak** [comment]
@sylvansson of course, just let me know when you're finished testing.

**Comment by sylvansson** [comment]
@mzilak I was wrong—boards are not added automatically. I'm not sure sure why I thought that they were yesterday. 

The issue seems to be that we don't erase the local storage when a user logs in, so the state still contains boards that were created or imported while logged out. Therefore, if we import a board "B" while unauthenticated, log in, then try to import it again, there already exists a board with the id "B" in the state so we skip it.

@martinbedouret Do you want to take this one or would you prefer I do it?

**Comment by sylvansson** [comment]
@mzilak I tested with the account and data in https://github.com/cboard-org/cboard/issues/789#issuecomment-699988029 and I was able to import the boards successfully. I'm guessing your local storage contained "bad" boards as explained in my previous comment.

**Comment by mzilak** [comment]
@sylvansson , that is probably it because I tried to import the boards after I "accidentally" imported them while logged out.
Also, I'll change the login data for account for testing.
